### ISSUE TITLE
Pickle files storing frequency data

### ISSUE THREAD

**Issue by zhaohengz** [baldassarreFe/ws-vrd#2]
Hi, 

Thanks for sharing the code.

I am trying to run the model locally and find that some pickle files containing frequency priors are missing. Would you mind sharing the file or pointing out the generation code is?

Thanks a lot for your help.

Best,
Zhaoheng

**Comment by baldassarreFe** [comment]
Hi, the code generation should be in the notebooks, but I just uploaded the files anyway:
```
data
├── unrel
│   └── processed
│       ├── prob_s_o_given_p.pkl.xz
│       └── prob_s_p_o.pkl.xz
├── unrel_vrd
│   └── processed
│       ├── prob_s_o_given_p.pkl.xz
│       └── prob_s_p_o.pkl.xz
└── vrd
    └── processed
        ├── prob_s_o_given_p.pkl.xz
        └── prob_s_p_o.pkl.xz
```

**Comment by SherlockHolmes221** [comment]
Could you provide the training data of HICO-DET and the trained model?
Thanks a lot!

**Comment by baldassarreFe** [comment]
Hi, I missed this message because the issue is closed. Can you open another issue for this?
Anyway, to answer your question, the training data for HICO-DET is available on their website so I won't replicate it here, but I'll upload the preprocessing code and the trained model.

**Comment by SherlockHolmes221** [comment]
Thanks
