### ISSUE TITLE
AttributeError: 'DefaultPredictor' object has no attribute 'transform_gen'

### ISSUE THREAD

**Issue by ZhuPeipei-CUHKSZ-TJUTCM** [baldassarreFe/ws-vrd#3]
Thanks for sharing your code. I have run your code and faced one problem when runing
------------------------------------------------------------------------------
python -m xib.preprocessing.hico_det \
  --skip-existing \
  --confidence-threshold=.3 \
  --nms-threshold=.7 \
  --hico-dir="./data" \
  --output-dir="data/hico_20160224_det/processed"
--------------------------------------------------------------------------------
That is "AttributeError: 'DefaultPredictor' object has no attribute 'transform_gen'", so can you help me solve it? Thanks a lot.

**Comment by aryanpandey** [comment]
Hey!
I'm facing the same issue, could you let me know how you resolved this?
Thanks in advance
